window.LITTLE_WEEKENDS_EVERGREEN = [
  {
    id: "badm-evergreen",
    name: "Bay Area Discovery Museum",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Sausalito",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "입장권 권장",
    source: "https://bayareadiscoverymuseum.org/plan-your-visit/",
    sourceName: "Bay Area Discovery Museum",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "557 McReynolds Road, Sausalito, CA 94965",
    why: "0-3세 전용 Tot Spot과 실내외 체험 공간이 있어 어린 동생과 함께 가기 좋아요.",
    notes: {
      parking: "박물관 옆 무료 주차장을 이용할 수 있어요.",
      bathroom: "모든 화장실에 기저귀 교환대가 있고 가족 편의시설이 있어요.",
      stroller: "유모차 이동이 가능하고 수유 공간도 마련되어 있어요."
    },
    location: { lat: 37.8356, lng: -122.4764 }
  },
  {
    id: "sonoma-traintown",
    name: "Sonoma TrainTown Railroad",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "계절 운영",
    city: "Sonoma",
    age: "1-6세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 83,
    price: "paid",
    reservation: "날씨·운영일 확인",
    source: "https://www.traintown.com/park-info",
    sourceName: "Sonoma TrainTown Railroad",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "20264 Broadway, Sonoma, CA 95476",
    why: "20분 기차와 작은 놀이기구가 있어 기차를 좋아하는 유아에게 목적이 분명한 나들이예요.",
    notes: {
      parking: "입장과 주차는 무료이고 놀이기구별 티켓을 구매해요.",
      bathroom: "공원 내 편의시설 위치를 입장 후 확인하세요.",
      stroller: "야외 이동이 많아 유모차를 가져가면 편해요."
    },
    location: { lat: 38.2879, lng: -122.4584 }
  },
  {
    id: "presidio-outpost",
    name: "Presidio Tunnel Tops Outpost",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "San Francisco",
    age: "2-12세",
    minAgeMonths: 24,
    maxAgeMonths: 155,
    price: "free",
    reservation: "예약 불필요",
    source: "https://presidio.gov/explore/attractions/outpost-playground",
    sourceName: "The Presidio",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "210 Lincoln Boulevard, San Francisco, CA 94129",
    why: "2세부터 즐길 수 있는 자연형 놀이터와 어린아이 탐색 구역이 있고 무료예요.",
    notes: {
      parking: "Visitor Center 주변 유료 주차장 또는 Presidio GO를 이용하세요.",
      bathroom: "Field Station 옆에 휠체어 접근 가능한 가족 화장실이 있어요.",
      stroller: "포장 동선과 유모차 주차 공간을 이용할 수 있어요."
    },
    location: { lat: 37.7996, lng: -122.4662 }
  },
  {
    id: "childrens-creativity-museum",
    name: "Children's Creativity Museum",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "수-일 운영",
    city: "San Francisco",
    age: "2-8세",
    minAgeMonths: 24,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "티켓 확인",
    source: "https://creativity.org/",
    sourceName: "Children's Creativity Museum",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "221 Fourth Street, San Francisco, CA 94103",
    why: "만들기와 음악 중심의 손으로 만지는 전시라 비 오는 날 짧게 놀기 좋아요.",
    notes: {
      parking: "Yerba Buena 주변 유료 주차 또는 대중교통을 이용하세요.",
      bathroom: "박물관 내 화장실을 이용할 수 있어요.",
      stroller: "실내 이동은 가능하지만 붐비는 시간에는 접이식이 편해요."
    },
    location: { lat: 37.7834, lng: -122.4020 }
  },
  {
    id: "randall-museum",
    name: "Randall Museum",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "화-토 운영",
    city: "San Francisco",
    age: "1-8세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://randallmuseum.org/about-us/faqs/",
    sourceName: "Randall Museum",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "199 Museum Way, San Francisco, CA 94114",
    why: "무료 동물·과학 전시와 toddler playroom이 있어 부담 없이 들르기 좋아요.",
    notes: {
      parking: "Museum Way 주변 주차 상황을 확인하세요.",
      bathroom: "시설 내 화장실을 이용할 수 있어요.",
      stroller: "실내 전시와 야외 전망 공간을 함께 이동할 수 있어요."
    },
    location: { lat: 37.7645, lng: -122.4384 }
  },
  {
    id: "koret-childrens-quarter",
    name: "Koret Children's Quarter",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "San Francisco",
    age: "1-8세",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.sfrecpark.org/Facilities/Facility/Details/Koret-Childrens-Quarter-and-Carousel-414",
    sourceName: "San Francisco Recreation and Parks",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "320 Bowling Green Drive, San Francisco, CA 94121",
    why: "접근 가능한 놀이 공간과 넓은 잔디, 회전목마를 한 동선에서 즐길 수 있어요.",
    notes: {
      parking: "Bowling Green Drive 동쪽 주차 구역을 확인하세요.",
      bathroom: "접근 가능한 공중 화장실이 있어요.",
      stroller: "Golden Gate Park 포장 산책로로 접근하기 편해요."
    },
    location: { lat: 37.7674, lng: -122.4830 }
  },
  {
    id: "san-francisco-zoo",
    name: "San Francisco Zoo",
    type: "museum",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "San Francisco",
    age: "1-6세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 83,
    price: "paid",
    reservation: "티켓 권장",
    source: "https://www.sfzoo.org/",
    sourceName: "San Francisco Zoo",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "Sloat Boulevard at Great Highway, San Francisco, CA 94132",
    why: "동물 관찰과 어린이 놀이 공간을 섞어 반나절 일정으로 구성하기 좋아요.",
    notes: {
      parking: "유료 주차장과 Great Highway 주변 교통을 확인하세요.",
      bathroom: "원내 여러 화장실과 가족 편의시설을 이용할 수 있어요.",
      stroller: "동선이 길어 유모차를 가져가는 편이 좋아요."
    },
    location: { lat: 37.7328, lng: -122.5030 }
  },
  {
    id: "hiller-aviation",
    name: "Hiller Aviation Museum",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "San Carlos",
    age: "2-8세·가족",
    minAgeMonths: 24,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "예약 불필요",
    source: "https://www.hiller.org/visit/",
    sourceName: "Hiller Aviation Museum",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "601 Skyway Road, San Carlos, CA 94070",
    why: "실내 비행기 전시와 어린아이용 블록 놀이가 있어 비 오는 날 활용하기 좋아요.",
    notes: {
      parking: "박물관 전용 무료 주차장이 있어요.",
      bathroom: "시설 내 화장실을 이용할 수 있어요.",
      stroller: "넓은 실내 전시 동선으로 유모차 이동이 쉬운 편이에요."
    },
    location: { lat: 37.5129, lng: -122.2515 }
  },
  {
    id: "magical-bridge-palo-alto",
    name: "Magical Bridge Playground",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "일출-일몰",
    city: "Palo Alto",
    age: "1-8세·전 능력",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.paloalto.gov/Departments/Community-Services/Parks-Open-Space-Golf-Division/Neighborhood-Parks/Mitchell-Park/Magical-Bridge-Playground",
    sourceName: "City of Palo Alto",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "3700 Middlefield Road, Palo Alto, CA 94303",
    why: "감각 휴식 공간과 연령·능력별 놀이 구역이 분리된 무료 포용형 놀이터예요.",
    notes: {
      parking: "Mitchell Park 주차장을 이용하세요.",
      bathroom: "공원 내 화장실과 음수대를 이용할 수 있어요.",
      stroller: "놀이터 안에는 유모차 반입이 제한되어 지정 공간에 세워야 해요."
    },
    location: { lat: 37.4222, lng: -122.1147 }
  },
  {
    id: "childrens-discovery-san-jose",
    name: "Children's Discovery Museum of San Jose",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "화-일 운영",
    city: "San Jose",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "티켓 권장",
    source: "https://www.cdm.org/",
    sourceName: "Children's Discovery Museum of San Jose",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "180 Woz Way, San Jose, CA 95110",
    why: "물놀이와 0-4세용 Wonder Cabinet 등 어린아이 체험이 많아 긴 실내 일정에 좋아요.",
    notes: {
      parking: "Woz Way 주변 공영 유료 주차장을 이용하세요.",
      bathroom: "시설 내 가족 화장실을 이용할 수 있어요.",
      stroller: "걷기 어려운 아이를 위한 유모차만 내부 사용이 가능해요."
    },
    location: { lat: 37.3268, lng: -121.8929 }
  },
  {
    id: "happy-hollow",
    name: "Happy Hollow Park & Zoo",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "San Jose",
    age: "1-8세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "티켓 권장",
    source: "https://happyhollow.org/visit-/",
    sourceName: "Happy Hollow Park & Zoo",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "748 Story Road, San Jose, CA 95112",
    why: "작은 동물원, 유아 놀이 구조물, 가족 놀이기구가 한곳에 있어 반나절 보내기 좋아요.",
    notes: {
      parking: "Story Road 또는 Senter Road 유료 주차장을 이용하세요.",
      bathroom: "원내 화장실과 피크닉 공간을 이용할 수 있어요.",
      stroller: "원내 동선이 넓어 유모차 이동이 가능해요."
    },
    location: { lat: 37.3256, lng: -121.8613 }
  },
  {
    id: "rotary-playgarden",
    name: "Rotary PlayGarden",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "목-일 운영",
    city: "San Jose",
    age: "1-8세·전 능력",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "free",
    reservation: "운영시간 확인",
    source: "https://grpg.org/visit/guadalupe-gardens/rotary-playgarden/",
    sourceName: "Guadalupe River Park Conservancy",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "438 Coleman Avenue, San Jose, CA 95110",
    why: "그늘과 접근 가능한 놀이 구조물이 잘 갖춰진 무료 포용형 놀이터예요.",
    notes: {
      parking: "Visitor Center 주변 주차 안내를 확인하세요.",
      bathroom: "Visitor Center 운영시간과 화장실 이용 가능 여부를 확인하세요.",
      stroller: "평탄한 접근 동선으로 유모차 이동이 편해요."
    },
    location: { lat: 37.3418, lng: -121.9035 }
  },
  {
    id: "emma-prusch-farm",
    name: "Emma Prusch Farm Regional Park",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "San Jose",
    age: "2-5세",
    minAgeMonths: 24,
    maxAgeMonths: 71,
    price: "free",
    reservation: "일부 동물 구역 공사 확인",
    source: "https://www.sanjoseca.gov/Home/Components/FacilityDirectory/FacilityDirectory/2180/2028",
    sourceName: "City of San Jose",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "647 S. King Road, San Jose, CA 95116",
    why: "2-5세 놀이터와 농장 풍경을 무료로 즐길 수 있어 짧은 야외 나들이에 좋아요.",
    notes: {
      parking: "공원 무료 주차장을 이용할 수 있어요.",
      bathroom: "공원 내 화장실이 있어요.",
      stroller: "넓은 공원 동선이라 유모차나 왜건이 편해요."
    },
    location: { lat: 37.3417, lng: -121.8453 }
  },
  {
    id: "childrens-fairyland",
    name: "Children's Fairyland",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "Oakland",
    age: "0-8세",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "티켓 확인",
    source: "https://fairyland.org/visit/",
    sourceName: "Children's Fairyland",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "699 Bellevue Avenue, Oakland, CA 94610",
    why: "0-8세를 위해 만든 작은 놀이공원이라 1-3세가 직접 즐길 수 있는 요소가 많아요.",
    notes: {
      parking: "Lakeside Park 유료 주차장을 이용하세요.",
      bathroom: "공원 내 가족 편의시설을 이용할 수 있어요.",
      stroller: "야외 동선이 길어 유모차를 가져가는 편이 좋아요."
    },
    location: { lat: 37.8066, lng: -122.2588 }
  },
  {
    id: "oakland-zoo",
    name: "Oakland Zoo Children's Zoo",
    type: "museum",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Oakland",
    age: "1-8세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "paid",
    reservation: "사전 티켓 필요",
    source: "https://www.oaklandzoo.org/explore-the-zoo/",
    sourceName: "Oakland Zoo",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "9777 Golf Links Road, Oakland, CA 94605",
    why: "Children's Zoo 안에 작은 동물과 기어 다니며 탐색하는 놀이 요소가 있어요.",
    notes: {
      parking: "동물원 유료 주차와 사전 입장권을 함께 예약하세요.",
      bathroom: "원내 여러 화장실을 이용할 수 있어요.",
      stroller: "경사가 있고 동선이 길어 유모차를 권장해요."
    },
    location: { lat: 37.7508, lng: -122.1477 }
  },
  {
    id: "lawrence-hall-science",
    name: "The Lawrence Hall of Science",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "Berkeley",
    age: "2-6세",
    minAgeMonths: 24,
    maxAgeMonths: 83,
    price: "paid",
    reservation: "티켓 권장",
    source: "https://lawrencehallofscience.org/visitors/plan-your-visit/",
    sourceName: "The Lawrence Hall of Science",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "1 Centennial Drive, Berkeley, CA 94720",
    why: "2-6세용 Curiosity Corner와 6세 이하 Playtopia가 있어 어린아이도 즐길 수 있어요.",
    notes: {
      parking: "UC Berkeley 유료 주차장을 이용하세요.",
      bathroom: "시설 내 접근 가능한 화장실을 이용할 수 있어요.",
      stroller: "실내 전시 동선은 접근 가능하지만 주차장에서 경사를 고려하세요."
    },
    location: { lat: 37.8793, lng: -122.2467 }
  },
  {
    id: "tilden-little-farm",
    name: "Tilden Little Farm",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "Berkeley",
    age: "1-6세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 83,
    price: "free",
    reservation: "동물 먹이주기 중단",
    source: "https://www.ebparks.org/parks/tilden-nature-area",
    sourceName: "East Bay Regional Park District",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "600 Canon Drive, Berkeley, CA 94708",
    why: "소·양·염소 등 농장 동물을 가까이서 보고 짧은 자연 산책을 무료로 할 수 있어요.",
    notes: {
      parking: "Little Farm 인근 주차장 문 닫는 시간을 확인하세요.",
      bathroom: "Environmental Education Center 주변 시설을 확인하세요.",
      stroller: "보드워크와 완만한 길은 유모차로 이동하기 좋아요."
    },
    location: { lat: 37.9098, lng: -122.2654 }
  },
  {
    id: "lindsay-wildlife",
    name: "Lindsay Wildlife Experience",
    type: "museum",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Walnut Creek",
    age: "2-6세",
    minAgeMonths: 24,
    maxAgeMonths: 83,
    price: "paid",
    reservation: "티켓 확인",
    source: "https://lindsaywildlife.org/hours-prices-directions/",
    sourceName: "Lindsay Wildlife Experience",
    updated: "7월 12일 직접 확인",
    lastReviewedAt: "2026-07-12",
    confidenceStatus: "human_verified",
    address: "1931 First Avenue, Walnut Creek, CA 94597",
    why: "작은 실내 야생동물 전시와 2-5세용 프로그램 기반이 있어 짧게 집중하기 좋아요.",
    notes: {
      parking: "주거 지역 주변 주차 안내를 공식 페이지에서 확인하세요.",
      bathroom: "시설 내 화장실을 이용할 수 있어요.",
      stroller: "작은 실내 공간이라 접이식 유모차가 편해요."
    },
    location: { lat: 37.9211, lng: -122.0751 }
  },
  {
    id: "redwood-shores-library",
    name: "Redwood Shores Branch Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "월-목·주말 운영",
    city: "Redwood City",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.redwoodcity.org/departments/library/locations-and-hours",
    sourceName: "Redwood City Public Library",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "399 Marine Parkway, Redwood City, CA 94065",
    why: "어린이 공간과 유아용 터치스크린 기기가 있고 무료 주차장을 이용할 수 있어 짧은 실내 나들이로 좋아요.",
    notes: {
      parking: "도서관 전용 무료 주차장을 이용할 수 있어요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "도서관 출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.5311, lng: -122.2587 }
  },
  {
    id: "redwood-city-downtown-library",
    name: "Redwood City Downtown Library Family Place",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "Redwood City",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.redwoodcity.org/departments/library/locations-and-hours",
    sourceName: "Redwood City Public Library",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "1044 Middlefield Road, Redwood City, CA 94063",
    why: "어린이용 Family Place와 그림책 공간이 있어 행사 시간이 아니어도 아이와 편하게 머물기 좋아요.",
    notes: {
      parking: "도서관 주차장은 유료이며 Jefferson Garage는 평일 1시간 30분 무료예요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "넓은 출입구와 실내 동선으로 유모차 이동이 가능해요."
    },
    location: { lat: 37.4844, lng: -122.2286 }
  },
  {
    id: "redwood-city-magical-bridge",
    name: "Magical Bridge Playground at Red Morton Park",
    type: "park",
    setting: "outdoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "Redwood City",
    age: "1-8세·가족",
    minAgeMonths: 12,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.redwoodcity.org/Home/Components/FacilityDirectory/FacilityDirectory/51/",
    sourceName: "City of Redwood City",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "1120 Roosevelt Avenue, Redwood City, CA 94061",
    why: "전 연령·전 능력을 위한 놀이터와 유아 구역, 감각 물놀이 공간이 있어 형제자매와 함께 가기 좋아요.",
    notes: {
      parking: "Red Morton Park 주변 주차장을 이용할 수 있어요.",
      bathroom: "공원 내 화장실이 있어요.",
      stroller: "포장 동선으로 놀이터까지 유모차 접근이 가능해요."
    },
    location: { lat: 37.4869, lng: -122.2470 }
  },
  {
    id: "belmont-library-family-place",
    name: "Belmont Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Belmont",
    age: "0-11세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 143,
    price: "free",
    reservation: "예약 불필요",
    source: "https://smcl.org/locations/1b/",
    sourceName: "San Mateo County Libraries",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "1110 Alameda de las Pulgas, Belmont, CA 94002",
    why: "어린이 공간과 정기 영유아 프로그램이 있어 행사 전후에도 책과 놀이를 이어가기 좋아요.",
    notes: {
      parking: "도서관 주차장과 주변 주차 안내를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.5087978, lng: -122.2932556 }
  },
  {
    id: "foster-city-library-family-place",
    name: "Foster City Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Foster City",
    age: "0-11세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 143,
    price: "free",
    reservation: "예약 불필요",
    source: "https://smcl.org/locations/1f/",
    sourceName: "San Mateo County Libraries",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "1000 E Hillsdale Boulevard, Foster City, CA 94404",
    why: "영유아 스토리타임과 만들기 프로그램이 꾸준해 비 오는 날에도 가볍게 들르기 좋아요.",
    notes: {
      parking: "도서관 주변 공용 주차 안내를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.5585908, lng: -122.2704718 }
  },
  {
    id: "san-carlos-library-family-place",
    name: "San Carlos Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "San Carlos",
    age: "0-11세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 143,
    price: "free",
    reservation: "예약 불필요",
    source: "https://smcl.org/locations/1s/",
    sourceName: "San Mateo County Libraries",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "610 Elm Street, San Carlos, CA 94070",
    why: "아기 프로그램부터 초등 저학년 만들기까지 연령 폭이 넓어 형제자매와 함께 가기 좋아요.",
    notes: {
      parking: "도서관 주변 공영·노상 주차 안내를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 프로그램 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.5036235, lng: -122.2623139 }
  },
  {
    id: "millbrae-library-family-place",
    name: "Millbrae Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Millbrae",
    age: "0-11세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 143,
    price: "free",
    reservation: "예약 불필요",
    source: "https://smcl.org/locations/1m/",
    sourceName: "San Mateo County Libraries",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "1 Library Avenue, Millbrae, CA 94030",
    why: "아기 스토리타임과 메이커 프로그램을 함께 운영해 연령에 맞춰 선택하기 좋아요.",
    notes: {
      parking: "도서관 주차장과 주변 주차 안내를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.6023064, lng: -122.3969516 }
  },
  {
    id: "burlingame-main-library-family-place",
    name: "Burlingame Public Library, Main",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "매일 운영",
    city: "Burlingame",
    age: "0-11세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 143,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.burlingame.org/1108/Main-Library",
    sourceName: "Burlingame Public Library",
    updated: "7월 13일 공식 확인",
    lastReviewedAt: "2026-07-13",
    confidenceStatus: "human_verified",
    address: "480 Primrose Road, Burlingame, CA 94010",
    why: "주중·주말 모두 운영하고 아기부터 5세까지 정기 스토리타임이 있어 가까운 실내 나들이로 좋아요.",
    notes: {
      parking: "도서관 주변 공영·노상 주차 안내를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.5777, lng: -122.3482 }
  },
  {
    id: "palo-alto-childrens-library",
    name: "Palo Alto Children's Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Palo Alto",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://library.cityofpaloalto.org/locations/c/",
    sourceName: "Palo Alto City Library",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "1276 Harriet Street, Palo Alto, CA 94301",
    why: "어린이를 위해 설계된 별도 도서관으로 영유아 책과 정기 스토리타임을 함께 이용하기 좋아요.",
    notes: {
      parking: "주변 노상 주차와 운영 안내를 공식 장소 페이지에서 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 열람 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4462, lng: -122.1478 }
  },
  {
    id: "palo-alto-mitchell-park-library",
    name: "Mitchell Park Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Palo Alto",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://library.cityofpaloalto.org/locations/m/",
    sourceName: "Palo Alto City Library",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "3700 Middlefield Road, Palo Alto, CA 94303",
    why: "가족 스토리타임과 Music & Movement가 열리고 같은 공원 안에 놀이터가 있어 연계하기 좋아요.",
    notes: {
      parking: "Mitchell Park 공용 주차장을 이용할 수 있어요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4223, lng: -122.1127 }
  },
  {
    id: "palo-alto-rinconada-library",
    name: "Rinconada Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Palo Alto",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://library.cityofpaloalto.org/locations/r/",
    sourceName: "Palo Alto City Library",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "1213 Newell Road, Palo Alto, CA 94303",
    why: "넓은 어린이 공간과 가족 프로그램이 있고 Rinconada Park와 함께 이용하기 좋은 도서관이에요.",
    notes: {
      parking: "도서관 전용 주차장과 주변 주차 안내를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4450, lng: -122.1392 }
  },
  {
    id: "palo-alto-downtown-library",
    name: "Downtown Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Palo Alto",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://library.cityofpaloalto.org/locations/d/",
    sourceName: "Palo Alto City Library",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "270 Forest Avenue, Palo Alto, CA 94301",
    why: "금요일 가족 스토리타임과 다운타운 산책을 짧게 묶기 좋은 소규모 도서관이에요.",
    notes: {
      parking: "다운타운 공영·노상 주차 정보를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4439, lng: -122.1592 }
  },
  {
    id: "palo-alto-college-terrace-library",
    name: "College Terrace Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Palo Alto",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://library.cityofpaloalto.org/locations/t/",
    sourceName: "Palo Alto City Library",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "2300 Wellesley Street, Palo Alto, CA 94306",
    why: "영어·스페인어 가족 스토리타임 등 작은 지점 특유의 가까운 분위기를 이용하기 좋아요.",
    notes: {
      parking: "주변 노상 주차와 운영 안내를 공식 장소 페이지에서 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 프로그램 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4234, lng: -122.1486 }
  },
  {
    id: "menlo-park-library-family-place",
    name: "Menlo Park Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Menlo Park",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.menlopark.gov/Government/Departments/Library-and-Community-Services/Library/About-the-library/Hours-and-locations",
    sourceName: "City of Menlo Park",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "800 Alma Street, Menlo Park, CA 94025",
    why: "목·금·토 가족 스토리타임과 어린이 행사가 이어져 일정 선택지가 많은 도서관이에요.",
    notes: {
      parking: "도서관 주변 주차 정보를 공식 장소 페이지에서 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4521, lng: -122.1778 }
  },
  {
    id: "belle-haven-library-family-place",
    name: "Belle Haven Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Menlo Park",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://www.menlopark.gov/Government/Departments/Library-and-Community-Services/Library/About-the-library/Hours-and-locations",
    sourceName: "City of Menlo Park",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "100 Terminal Avenue, Menlo Park, CA 94025",
    why: "화·금·토 가족 스토리타임과 커뮤니티 캠퍼스의 가족 프로그램을 함께 이용하기 좋아요.",
    notes: {
      parking: "Belle Haven Community Campus 주차 정보를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "커뮤니티 캠퍼스 출입구와 도서관까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.4770, lng: -122.1600 }
  },
  {
    id: "mountain-view-public-library-family-place",
    name: "Mountain View Public Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Mountain View",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://library.mountainview.gov/",
    sourceName: "Mountain View Public Library",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "585 Franklin Street, Mountain View, CA 94041",
    why: "아기·토들러·프리스쿨 대상 일정과 Pioneer Park 야외 스토리타임을 함께 찾기 좋은 도서관이에요.",
    notes: {
      parking: "Franklin Street와 주변 공영 주차 정보를 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.3992, lng: -122.1095 }
  },
  {
    id: "cupertino-library-family-place",
    name: "Cupertino Library",
    type: "indoor",
    setting: "indoor",
    dateBucket: "anytime",
    timeLabel: "운영시간 확인",
    city: "Cupertino",
    age: "0-8세·가족",
    minAgeMonths: 0,
    maxAgeMonths: 107,
    price: "free",
    reservation: "예약 불필요",
    source: "https://sccld.org/locations/cupertino/",
    sourceName: "Santa Clara County Library District",
    updated: "7월 16일 공식 확인",
    lastReviewedAt: "2026-07-16",
    confidenceStatus: "human_verified",
    address: "10800 Torre Avenue, Cupertino, CA 95014",
    why: "아기·토들러·가족 스토리타임과 넓은 어린이 공간을 함께 이용할 수 있는 대형 도서관이에요.",
    notes: {
      parking: "Civic Center 주변 주차 정보를 공식 장소 페이지에서 확인하세요.",
      bathroom: "도서관 내 화장실을 이용할 수 있어요.",
      stroller: "출입구와 어린이 공간까지 유모차로 이동할 수 있어요."
    },
    location: { lat: 37.3183, lng: -122.0287 }
  }
];
