window.LITTLE_WEEKENDS_PLACE_IMAGES = Object.freeze({
  "childrens-creativity-museum": {
    src: "assets/places/childrens-creativity-museum.webp",
    kind: "actual",
    alt: "밤에 불이 켜진 Children's Creativity Museum과 회전목마",
    creator: "mliu92",
    credit: "mliu92 · Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Children%27s_Creativity_Museum_(was_%27Zeum%27)_(24969394294).jpg",
    commonsPageId: 47413891,
    verifiedAt: "2026-07-26",
    aliases: ["Children's Creativity Museum"]
  },
  "randall-museum": {
    src: "assets/places/randall-museum.webp",
    kind: "actual",
    alt: "Randall Museum 건물과 입구 표지",
    creator: "Piotrus",
    credit: "Piotrus · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:San_Francisco_-_Randall_Museum_02.JPG",
    commonsPageId: 8825877,
    verifiedAt: "2026-07-26",
    aliases: ["Randall Museum"]
  },
  "san-francisco-zoo": {
    src: "assets/places/san-francisco-zoo.webp",
    kind: "actual",
    alt: "San Francisco Zoo의 플라밍고 전시 공간",
    creator: "Daderot",
    credit: "Daderot · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flamingos_-_San_Francisco_Zoo_-_San_Francisco,_CA_-_DSC03515.jpg",
    commonsPageId: 50254848,
    verifiedAt: "2026-07-26",
    aliases: ["San Francisco Zoo"]
  },
  "childrens-discovery-san-jose": {
    src: "assets/places/childrens-discovery-museum-san-jose.webp",
    kind: "actual",
    alt: "보라색 외관의 Children's Discovery Museum of San Jose",
    creator: "LPS.1",
    credit: "LPS.1 · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Children%27s_Discovery_Museum_of_San_Jose.jpg",
    commonsPageId: 23527205,
    verifiedAt: "2026-07-26",
    aliases: ["Children's Discovery Museum of San Jose"]
  },
  "happy-hollow": {
    src: "assets/places/happy-hollow.webp",
    kind: "actual",
    alt: "Happy Hollow Park & Zoo 입구",
    creator: "Don DeBold",
    credit: "Don DeBold · Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Happy_Hollow_Park_%26_Zoo_-San_Jose,_California,_USA-2Oct2011_(1).jpg",
    commonsPageId: 16856387,
    verifiedAt: "2026-07-26",
    aliases: ["Happy Hollow Park & Zoo"]
  },
  "sfpl-main-library-family-place": {
    src: "assets/places/sfpl-main-library.webp",
    kind: "actual",
    alt: "San Francisco Public Library Main Library 외관",
    creator: "J. Ash Bowie",
    credit: "J. Ash Bowie · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:SFPL_Main_Library_Full_Exterior.jpg",
    commonsPageId: 4567449,
    verifiedAt: "2026-07-26",
    aliases: ["SFPL Main Library", "San Francisco Public Library Main Library"]
  },
  "hiller-aviation": {
    src: "assets/places/hiller-aviation-museum.webp",
    kind: "actual",
    alt: "Hiller Aviation Museum의 초기 항공기 전시",
    creator: "Ed Bierman",
    credit: "Ed Bierman · Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Early_Flight_(3029749435).jpg",
    commonsPageId: 26445992,
    verifiedAt: "2026-07-26",
    aliases: ["Hiller Aviation Museum"]
  },
  "emma-prusch-farm": {
    src: "assets/places/emma-prusch-farm.webp",
    kind: "actual",
    alt: "Emma Prusch Farm Regional Park의 역사적인 농가",
    creator: "Grey3k",
    credit: "Grey3k · Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:EmmaPruschFarmhouse.jpg",
    commonsPageId: 4732779,
    verifiedAt: "2026-07-26",
    aliases: ["Emma Prusch Farm Regional Park"]
  },
  "lawrence-hall-science": {
    src: "assets/places/lawrence-hall-of-science.webp",
    kind: "actual",
    alt: "언덕 위 The Lawrence Hall of Science 건물",
    creator: "Lasthib",
    credit: "Lasthib · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Lawrence_hall_of_science_Berkeley.jpg",
    commonsPageId: 71696449,
    verifiedAt: "2026-07-26",
    aliases: ["The Lawrence Hall of Science", "Lawrence Hall of Science"]
  },
  "tilden-little-farm": {
    src: "assets/places/tilden-little-farm.webp",
    kind: "actual",
    alt: "Tilden Little Farm의 헛간과 농장 동물",
    creator: "Harmonywriter",
    credit: "Harmonywriter · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tilden_Regional_Park_little_farm.jpg",
    commonsPageId: 29716241,
    verifiedAt: "2026-07-26",
    aliases: ["Tilden Little Farm"]
  },
  "lindsay-wildlife": {
    src: "assets/places/lindsay-wildlife.webp",
    kind: "actual",
    alt: "Lindsay Wildlife Experience에서 보호 중인 회색여우",
    creator: "Milonica",
    credit: "Milonica · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gray_Fox_in_captivity.JPG",
    commonsPageId: 23415312,
    verifiedAt: "2026-07-26",
    aliases: ["Lindsay Wildlife Experience"]
  },
  "redwood-shores-library": {
    src: "assets/places/redwood-shores-library.webp",
    kind: "actual",
    alt: "Redwood Shores Branch Library 내부 열람 공간",
    creator: "Suiren2022",
    credit: "Suiren2022 · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Redwood_Shores_Branch_Library_-_2.jpg",
    commonsPageId: 136189785,
    verifiedAt: "2026-07-26",
    aliases: ["Redwood Shores Branch Library"]
  },
  "foster-city-library-family-place": {
    src: "assets/places/foster-city-library.webp",
    kind: "actual",
    alt: "Foster City Library 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Foster_City_Library,_exterior_(November_2024)_02.jpg",
    commonsPageId: 155533973,
    verifiedAt: "2026-07-26",
    aliases: ["Foster City Library"]
  },
  "belmont-library-family-place": {
    src: "assets/places/belmont-library.webp",
    kind: "actual",
    alt: "Belmont Library 건물과 표지",
    creator: "Mike Linksvayer",
    credit: "Mike Linksvayer · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Belmont_Library_(8017936131).jpg",
    commonsPageId: 50288500,
    verifiedAt: "2026-07-26",
    aliases: ["Belmont Library"]
  }
});
