(() => {
const reviewedPlaceImages = {
  "childrens-creativity-museum": {
    src: "assets/places/childrens-creativity-museum.webp",
    kind: "actual",
    alt: "밤에 불이 켜진 Children's Creativity Museum과 회전목마",
    creator: "mliu92",
    credit: "mliu92 · Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Children%27s_Creativity_Museum_(was_%27Zeum%27)_(24969394294).jpg",
    commonsPageId: 47413891,
    verifiedAt: "2026-07-26",
    aliases: ["Children's Creativity Museum"]
  },
  "randall-museum": {
    src: "assets/places/randall-museum.webp",
    kind: "actual",
    alt: "Randall Museum 건물과 입구 표지",
    creator: "Piotrus",
    credit: "Piotrus · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:San_Francisco_-_Randall_Museum_02.JPG",
    commonsPageId: 8825877,
    verifiedAt: "2026-07-26",
    aliases: ["Randall Museum"]
  },
  "san-francisco-zoo": {
    src: "assets/places/san-francisco-zoo.webp",
    kind: "actual",
    alt: "San Francisco Zoo의 플라밍고 전시 공간",
    creator: "Daderot",
    credit: "Daderot · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flamingos_-_San_Francisco_Zoo_-_San_Francisco,_CA_-_DSC03515.jpg",
    commonsPageId: 50254848,
    verifiedAt: "2026-07-26",
    aliases: ["San Francisco Zoo"]
  },
  "childrens-discovery-san-jose": {
    src: "assets/places/childrens-discovery-museum-san-jose.webp",
    kind: "actual",
    alt: "보라색 외관의 Children's Discovery Museum of San Jose",
    creator: "LPS.1",
    credit: "LPS.1 · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Children%27s_Discovery_Museum_of_San_Jose.jpg",
    commonsPageId: 23527205,
    verifiedAt: "2026-07-26",
    aliases: ["Children's Discovery Museum of San Jose"]
  },
  "happy-hollow": {
    src: "assets/places/happy-hollow.webp",
    kind: "actual",
    alt: "Happy Hollow Park & Zoo 입구",
    creator: "Don DeBold",
    credit: "Don DeBold · Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Happy_Hollow_Park_%26_Zoo_-San_Jose,_California,_USA-2Oct2011_(1).jpg",
    commonsPageId: 16856387,
    verifiedAt: "2026-07-26",
    aliases: ["Happy Hollow Park & Zoo"]
  },
  "sfpl-main-library-family-place": {
    src: "assets/places/sfpl-main-library.webp",
    kind: "actual",
    alt: "San Francisco Public Library Main Library 외관",
    creator: "J. Ash Bowie",
    credit: "J. Ash Bowie · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:SFPL_Main_Library_Full_Exterior.jpg",
    commonsPageId: 4567449,
    verifiedAt: "2026-07-26",
    aliases: ["SFPL Main Library", "San Francisco Public Library Main Library"]
  },
  "hiller-aviation": {
    src: "assets/places/hiller-aviation-museum.webp",
    kind: "actual",
    alt: "Hiller Aviation Museum의 초기 항공기 전시",
    creator: "Ed Bierman",
    credit: "Ed Bierman · Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Early_Flight_(3029749435).jpg",
    commonsPageId: 26445992,
    verifiedAt: "2026-07-26",
    aliases: ["Hiller Aviation Museum"]
  },
  "emma-prusch-farm": {
    src: "assets/places/emma-prusch-farm.webp",
    kind: "actual",
    alt: "Emma Prusch Farm Regional Park의 역사적인 농가",
    creator: "Grey3k",
    credit: "Grey3k · Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:EmmaPruschFarmhouse.jpg",
    commonsPageId: 4732779,
    verifiedAt: "2026-07-26",
    aliases: ["Emma Prusch Farm Regional Park"]
  },
  "lawrence-hall-science": {
    src: "assets/places/lawrence-hall-of-science.webp",
    kind: "actual",
    alt: "언덕 위 The Lawrence Hall of Science 건물",
    creator: "Lasthib",
    credit: "Lasthib · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Lawrence_hall_of_science_Berkeley.jpg",
    commonsPageId: 71696449,
    verifiedAt: "2026-07-26",
    aliases: ["The Lawrence Hall of Science", "Lawrence Hall of Science"]
  },
  "tilden-little-farm": {
    src: "assets/places/tilden-little-farm.webp",
    kind: "actual",
    alt: "Tilden Little Farm의 헛간과 농장 동물",
    creator: "Harmonywriter",
    credit: "Harmonywriter · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tilden_Regional_Park_little_farm.jpg",
    commonsPageId: 29716241,
    verifiedAt: "2026-07-26",
    aliases: ["Tilden Little Farm"]
  },
  "lindsay-wildlife": {
    src: "assets/places/lindsay-wildlife.webp",
    kind: "actual",
    alt: "Lindsay Wildlife Experience에서 보호 중인 회색여우",
    creator: "Milonica",
    credit: "Milonica · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gray_Fox_in_captivity.JPG",
    commonsPageId: 23415312,
    verifiedAt: "2026-07-26",
    aliases: ["Lindsay Wildlife Experience"]
  },
  "redwood-shores-library": {
    src: "assets/places/redwood-shores-library.webp",
    kind: "actual",
    alt: "Redwood Shores Branch Library 내부 열람 공간",
    creator: "Suiren2022",
    credit: "Suiren2022 · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Redwood_Shores_Branch_Library_-_2.jpg",
    commonsPageId: 136189785,
    verifiedAt: "2026-07-26",
    aliases: ["Redwood Shores Branch Library"]
  },
  "foster-city-library-family-place": {
    src: "assets/places/foster-city-library.webp",
    kind: "actual",
    alt: "Foster City Library 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Foster_City_Library,_exterior_(November_2024)_02.jpg",
    commonsPageId: 155533973,
    verifiedAt: "2026-07-26",
    aliases: ["Foster City Library"]
  },
  "belmont-library-family-place": {
    src: "assets/places/belmont-library.webp",
    kind: "actual",
    alt: "Belmont Library 건물과 표지",
    creator: "Mike Linksvayer",
    credit: "Mike Linksvayer · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Belmont_Library_(8017936131).jpg",
    commonsPageId: 50288500,
    verifiedAt: "2026-07-26",
    aliases: ["Belmont Library"]
  },
  "sonoma-traintown": {
    src: "assets/places/sonoma-traintown.jpg",
    kind: "actual",
    alt: "Sonoma TrainTown Railroad의 증기 기관차와 회전 관람차",
    creator: "Jeff Soares",
    credit: "Jeff Soares · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:TrainTowntrain.JPG",
    commonsPageId: 7758639,
    verifiedAt: "2026-07-27",
    aliases: ["Sonoma TrainTown Railroad", "TrainTown"]
  },
  "childrens-fairyland": {
    src: "assets/places/childrens-fairyland.jpg",
    kind: "actual",
    alt: "오클랜드 Children's Fairyland 입구 안내 표지",
    creator: "Ted Eytan",
    credit: "Ted Eytan · Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Childrens_Fairyland_Oakland_7315_(6525735831).jpg",
    commonsPageId: 23144222,
    verifiedAt: "2026-07-27",
    aliases: ["Children's Fairyland"]
  },
  "san-carlos-library-family-place": {
    src: "assets/places/san-carlos-library.jpg",
    kind: "actual",
    alt: "San Carlos Library 정면 입구와 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:San_Carlos_Library,_exterior_(November_2024).jpg",
    commonsPageId: 154924155,
    verifiedAt: "2026-07-27",
    aliases: ["San Carlos Library"]
  },
  "millbrae-library-family-place": {
    src: "assets/places/millbrae-library.jpg",
    kind: "actual",
    alt: "Millbrae Library 정면 입구와 벽면 표지",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Millbrae_Library,_exterior_(October_2024)_01.jpg",
    commonsPageId: 154673287,
    verifiedAt: "2026-07-27",
    aliases: ["Millbrae Library"]
  },
  "mountain-view-public-library-family-place": {
    src: "assets/places/mountain-view-public-library.jpg",
    kind: "actual",
    alt: "Pioneer Memorial Park에서 바라본 Mountain View Public Library 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mountain_View_Public_Library,_exterior_(April_2024)_01.jpg",
    commonsPageId: 166522867,
    verifiedAt: "2026-07-27",
    aliases: ["Mountain View Public Library"]
  },
  "los-gatos-library-family-place": {
    src: "assets/places/los-gatos-library.jpg",
    kind: "actual",
    alt: "나무 뒤로 보이는 Los Gatos Library 정면 외관",
    creator: "Ramkmeno",
    credit: "Ramkmeno · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Los_Gatos_Library.jpg",
    commonsPageId: 72980471,
    verifiedAt: "2026-07-27",
    aliases: ["Los Gatos Library"]
  },
  "sunnyvale-public-library-family-place": {
    src: "assets/places/sunnyvale-public-library.jpg",
    kind: "actual",
    alt: "Sunnyvale Public Library 정면 출입구",
    creator: "The Sands of Time 0",
    credit: "The Sands of Time 0 · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunnyvale_Public_Library_(January_2025).jpg",
    commonsPageId: 167167207,
    verifiedAt: "2026-07-27",
    aliases: ["Sunnyvale Public Library"]
  },
  "campbell-campbell-park": {
    src: "assets/places/campbell-park.jpg",
    kind: "actual",
    alt: "Campbell Park 입구 표지와 공원 산책로",
    creator: "Grendelkhan",
    credit: "Grendelkhan · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Entrance_to_Campbell_Park.jpg",
    commonsPageId: 146402042,
    verifiedAt: "2026-07-27",
    aliases: ["Campbell Park"]
  },
  "oakland-lincoln-square-park": {
    src: "assets/places/lincoln-square-park-oakland.jpg",
    kind: "actual",
    alt: "오클랜드 Lincoln Square Park의 벽화와 놀이터",
    creator: "Mliu92",
    credit: "Mliu92 · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lincoln_Square_Park,_Oakland.jpg",
    commonsPageId: 132448895,
    verifiedAt: "2026-07-27",
    aliases: ["Lincoln Square Park"]
  },
  "daly-city-gellert-park": {
    src: "assets/places/gellert-park.jpg",
    kind: "actual",
    alt: "나무 사이로 보이는 Gellert Park 운동장과 놀이 공간",
    creator: "Clyde Charles Brown",
    credit: "Clyde Charles Brown · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gellert_Park,_Daly_City,_California,_US.jpg",
    commonsPageId: 164230126,
    verifiedAt: "2026-07-27",
    aliases: ["Gellert Park"]
  },
  "south-san-francisco-orange-memorial-park": {
    src: "assets/places/orange-memorial-park.jpg",
    kind: "actual",
    alt: "Orange Memorial Park 잔디밭과 어린이 놀이터",
    creator: "BrokenSphere",
    credit: "BrokenSphere · Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Orange_Memorial_Park_1.JPG",
    commonsPageId: 11430891,
    verifiedAt: "2026-07-27",
    aliases: ["Orange Memorial Park"]
  },
  "los-gatos-oak-meadow-park-playground": {
    src: "assets/places/oak-meadow-park.jpg",
    kind: "actual",
    alt: "Oak Meadow Park의 Billy Jones Wildcat Railroad 역",
    creator: "Gregory Ford Henderson",
    credit: "Gregory Ford Henderson · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Billy_Jones_Railroad_station_in_Oak_Meadow_Park_Adjacent_to_Vasona_Lake_County_Park.jpg",
    commonsPageId: 120228146,
    verifiedAt: "2026-07-27",
    aliases: ["Oak Meadow Park Playground", "Oak Meadow Park"]
  },
  "alameda-lincoln-park": {
    src: "assets/places/lincoln-park-alameda.jpg",
    kind: "actual",
    alt: "알라메다 Lincoln Park의 배 모양 어린이 놀이터",
    creator: "Mliu92",
    credit: "Mliu92 · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lincoln_Park_7.jpg",
    commonsPageId: 132448886,
    verifiedAt: "2026-07-27",
    aliases: ["Lincoln Park"]
  },
  "mountain-view-mariposa-park": {
    src: "assets/places/mariposa-park.jpg",
    kind: "actual",
    alt: "Mariposa Park의 어린이 놀이터와 잔디 산책로",
    creator: "Steven Baltakatei Sandoval",
    credit: "Steven Baltakatei Sandoval · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mariposa_Park,_Mountain_View,_California,_March_2019.jpg",
    commonsPageId: 77387532,
    verifiedAt: "2026-07-27",
    aliases: ["Mariposa Park"]
  },
  "los-gatos-vasona-lake-county-park": {
    src: "assets/places/vasona-lake-county-park.jpg",
    kind: "actual",
    alt: "Vasona Lake County Park의 넓은 잔디밭과 나무",
    creator: "Gregory Ford Henderson",
    credit: "Gregory Ford Henderson · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vasona_Lake_County_Park_meadow_with_geese.jpg",
    commonsPageId: 120228151,
    verifiedAt: "2026-07-27",
    aliases: ["Vasona Lake County Park"]
  },
  "oakland-mosswood-park": {
    src: "assets/places/mosswood-park.jpg",
    kind: "actual",
    alt: "오클랜드 Mosswood Park의 잔디밭과 큰 나무",
    creator: "Mx. Granger",
    credit: "Mx. Granger · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mosswood_Park_1.jpg",
    commonsPageId: 134783526,
    verifiedAt: "2026-07-27",
    aliases: ["Mosswood Park"]
  },
  "palo-alto-downtown-library": {
    src: "assets/places/palo-alto-downtown-library.jpg",
    kind: "actual",
    alt: "횡단보도 건너편에서 본 Downtown Library 정면 입구",
    creator: "BrokenSegue",
    credit: "BrokenSegue · Wikimedia Commons · cropped, resized, and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Downtown_Palo_Alto_Library.jpg",
    commonsPageId: 178282856,
    verifiedAt: "2026-07-28",
    aliases: ["Downtown Library", "Palo Alto Downtown Library", "Downtown Palo Alto Library"]
  },
  "palo-alto-johnson-park": {
    src: "assets/places/palo-alto-johnson-park.jpg",
    kind: "actual",
    alt: "산책로와 잔디밭이 보이는 Johnson Park 전경",
    creator: "ECTran71",
    credit: "ECTran71 · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Doctor_E_E_Johnson_Park.jpg",
    commonsPageId: 164728963,
    verifiedAt: "2026-07-28",
    aliases: ["Johnson Park", "Doctor E. E. Johnson Park", "Dr. E. E. Johnson Park"]
  },
  "magical-bridge-palo-alto": {
    src: "assets/places/magical-bridge-palo-alto.jpg",
    kind: "actual",
    alt: "Adobe Creek 너머로 보이는 Magical Bridge Playground의 보행교와 놀이 구조물",
    creator: "Dicklyon",
    credit: "Dicklyon · Wikimedia Commons · cropped, resized, and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Adobe_Creek_at_Magic_Bridge_Playground_Mitchell_Park.jpg",
    commonsPageId: 81757272,
    verifiedAt: "2026-07-28",
    aliases: ["Magical Bridge Playground", "Magical Bridge", "Magic Bridge Playground", "Magical Bridge Playground at Mitchell Park"]
  },
  "palo-alto-mitchell-park": {
    src: "assets/places/palo-alto-mitchell-park.jpg",
    kind: "actual",
    alt: "Mitchell Park 입구 표지와 뒤편 놀이터",
    creator: "Victorgrigas",
    credit: "Victorgrigas · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mitchell_Park_(1).jpg",
    commonsPageId: 78475872,
    verifiedAt: "2026-07-28",
    aliases: ["Mitchell Park"]
  },
  "palo-alto-rinconada-library": {
    src: "assets/places/palo-alto-rinconada-library.jpg",
    kind: "actual",
    alt: "잔디 정원에서 바라본 Rinconada Library 입구와 외관",
    creator: "Michal Cierniak",
    credit: "Michal Cierniak · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Palo_Alto_Public_Library,_Main_Branch_-_panoramio.jpg",
    commonsPageId: 52570004,
    verifiedAt: "2026-07-28",
    aliases: ["Rinconada Library", "Palo Alto Main Library", "Palo Alto Public Library Main Branch", "Main Branch"]
  },
  "menlo-park-burgess-park": {
    src: "assets/places/menlo-park-burgess-park.jpg",
    kind: "actual",
    alt: "Burgess Park Pool의 야외 수영 레인과 데크",
    creator: "mjmonty",
    credit: "mjmonty · Flickr via Openverse · cropped, resized, and compressed",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://www.flickr.com/photos/mjmonty/2794250822",
    commonsPageId: null,
    verifiedAt: "2026-07-28",
    aliases: ["Burgess Park", "Burgess Park Pool", "Burgess Pool"]
  },
  "menlo-park-nealon-all-abilities-playground": {
    src: "assets/places/menlo-park-nealon-all-abilities-playground.jpg",
    kind: "actual",
    alt: "잔디밭 앞 Nealon Park와 City of Menlo Park 입구 표지",
    creator: "Näystin",
    credit: "Näystin · Flickr via Openverse · cropped, resized, and compressed",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://www.flickr.com/photos/naystin/2218427391",
    commonsPageId: null,
    verifiedAt: "2026-07-28",
    aliases: ["Nealon Park All-Abilities Playground", "Nealon Park Nature Play Area", "Nealon Park"]
  },
  "badm-evergreen": {
    src: "assets/places/badm-evergreen.jpg",
    kind: "actual",
    alt: "언덕에서 내려다본 Bay Area Discovery Museum 캠퍼스와 금문 해협",
    creator: "Sarbjit Bahga",
    credit: "Sarbjit Bahga · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bay_Area_Discovery_Museum.jpg",
    commonsPageId: 71082682,
    verifiedAt: "2026-07-28",
    aliases: ["Bay Area Discovery Museum", "Bay Area Discovery Museum at Fort Baker", "BADM"]
  },
  "presidio-outpost": {
    src: "assets/places/presidio-outpost.jpg",
    kind: "actual",
    alt: "새 식재 구역 너머로 보이는 Presidio Tunnel Tops Outpost 탐험 놀이터와 금문교",
    creator: "btwashburn",
    credit: "btwashburn · Flickr via Openverse · resized and compressed",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://www.flickr.com/photos/21608680@N00/52248266484",
    commonsPageId: null,
    verifiedAt: "2026-07-28",
    aliases: ["Presidio Tunnel Tops Outpost", "The Outpost", "Outpost exploration area", "Presidio Tunnel Tops"]
  },
  "koret-childrens-quarter": {
    src: "assets/places/koret-childrens-quarter.jpg",
    kind: "actual",
    alt: "Koret Children’s Quarter 안에 있는 Golden Gate Park Carousel의 원형 건물 외관",
    creator: "Daderot",
    credit: "Daderot · Wikimedia Commons · resized and compressed",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Carousel,_Golden_Gate_Park_-_San_Francisco,_CA_-_1.jpg",
    commonsPageId: 143596071,
    verifiedAt: "2026-07-28",
    aliases: ["Koret Children’s Quarter", "Koret Children's Quarter", "Children's Playground at Golden Gate Park", "Golden Gate Park Children's Playground", "Golden Gate Park Carousel"]
  },
  "sfpl-mission-bay-library-family-place": {
    src: "assets/places/sfpl-mission-bay-library-family-place.jpg",
    kind: "actual",
    alt: "4번가 모퉁이에서 본 Mission Bay Branch Library 외관과 입구",
    creator: "Eric E Castro",
    credit: "Eric E Castro · Wikimedia Commons · resized and compressed",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mission_Bay_Branch_(4505708037).jpg",
    commonsPageId: 64748397,
    verifiedAt: "2026-07-28",
    aliases: ["Mission Bay Branch Library", "Mission Bay Library", "San Francisco Public Library Mission Bay Branch"]
  },
  "sfpl-noe-valley-library-family-place": {
    src: "assets/places/sfpl-noe-valley-library-family-place.jpg",
    kind: "actual",
    alt: "장식 문양과 지점명이 보이는 Noe Valley Branch Library 정문",
    creator: "Eric E Castro",
    credit: "Eric E Castro · Wikimedia Commons · resized and compressed",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Noe_Valley_Branch_Library_(4487190741).jpg",
    commonsPageId: 64749466,
    verifiedAt: "2026-07-28",
    aliases: ["Noe Valley Branch Library", "Noe Valley Library", "San Francisco Public Library Noe Valley Branch"]
  },
  "sfpl-glen-park-library-family-place": {
    src: "assets/places/sfpl-glen-park-library-family-place.jpg",
    kind: "actual",
    alt: "길 건너에서 본 Glen Park Branch Library 정면 입구",
    creator: "Eric E Castro",
    credit: "Eric E Castro · Wikimedia Commons · resized and compressed",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Glen_Park_Branch_Library_(27459485380).jpg",
    commonsPageId: 64748327,
    verifiedAt: "2026-07-28",
    aliases: ["Glen Park Branch Library", "Glen Park Library", "San Francisco Public Library Glen Park Branch"]
  },
  "sfpl-richmond-library-family-place": {
    src: "assets/places/sfpl-richmond-library-family-place.jpg",
    kind: "actual",
    alt: "진입로와 야자수가 보이는 Richmond Branch Library 정면 외관",
    creator: "Oort1",
    credit: "Oort1 · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Carnegie_Richmond_Branch_Library.jpg",
    commonsPageId: 33684613,
    verifiedAt: "2026-07-28",
    aliases: ["Richmond Branch Library", "Richmond Library", "Carnegie Richmond Branch Library", "San Francisco Public Library Richmond Branch"]
  },
  "sfpl-sunset-library-family-place": {
    src: "assets/places/sfpl-sunset-library-family-place.jpg",
    kind: "actual",
    alt: "18번가에서 본 Sunset Branch Library 정면과 중앙 입구",
    creator: "Eric E Castro",
    credit: "Eric E Castro · Wikimedia Commons · resized and compressed",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunset_Branch_Library_(4504043356).jpg",
    commonsPageId: 64748456,
    verifiedAt: "2026-07-28",
    aliases: ["Sunset Branch Library", "Sunset Library", "San Francisco Public Library Sunset Branch"]
  },
  "sf-argonne-playground": {
    src: "assets/places/sf-argonne-playground.jpg",
    kind: "actual",
    alt: "ARGONNE PLAYGROUND 입구 표지와 뒤편 운동장",
    creator: "Ragesoss",
    credit: "Ragesoss · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Argonne_Playground.jpg",
    commonsPageId: 76222997,
    verifiedAt: "2026-07-28",
    aliases: ["Argonne Playground", "Argonne Park"]
  },
  "larkspur-piper-park": {
    src: "assets/places/larkspur-piper-park.jpg",
    kind: "actual",
    alt: "도로 옆 PIPER PARK 입구 표지와 테니스 시설",
    creator: "E bailey",
    credit: "E bailey · Wikimedia Commons · resized and compressed",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Piper_Park,_Larkspur,_CA_Sept_2025.jpg",
    commonsPageId: 174392835,
    verifiedAt: "2026-07-28",
    aliases: ["Piper Park", "Piper Park Larkspur"]
  },
  "santa-clara-central-park-library-family-place": {
    src: "assets/places/santa-clara-central-park-library-family-place.jpg",
    kind: "actual",
    alt: "보행로 건너편에서 본 Santa Clara Central Park Library 정면 입구",
    creator: "Coolcaesar",
    credit: "Coolcaesar · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Santa_Clara_Central_Park_Library.jpg",
    commonsPageId: 1037813,
    verifiedAt: "2026-07-28",
    aliases: ["Central Park Library", "Santa Clara Central Park Library", "Santa Clara City Library Central Park"]
  },
  "sunnyvale-seven-seas-park": {
    src: "assets/places/sunnyvale-seven-seas-park.jpg",
    kind: "actual",
    alt: "그늘막 아래 배 모양 놀이 구조물이 보이는 Seven Seas Park 놀이터",
    creator: "BrokenSegue",
    credit: "BrokenSegue · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Seven_Seas_Park_Playground_(Sunnyvale).jpg",
    commonsPageId: 129606982,
    verifiedAt: "2026-07-28",
    aliases: ["Seven Seas Park", "Seven Seas Park Playground"]
  },
  "cupertino-library-family-place": {
    src: "assets/places/cupertino-library-family-place.jpg",
    kind: "actual",
    alt: "Cupertino Civic Center 전경에서 본 Cupertino Library 건물과 중앙 광장",
    creator: "Robert Kim/City of Cupertino",
    credit: "Robert Kim/City of Cupertino · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cupertino_Civic_Center_Panorama.jpg",
    commonsPageId: 41727830,
    verifiedAt: "2026-07-28",
    aliases: ["Cupertino Library", "Cupertino Library Family Place", "Santa Clara County Library Cupertino"]
  },
  "cupertino-memorial-park": {
    src: "assets/places/cupertino-memorial-park.jpg",
    kind: "actual",
    alt: "Cupertino Memorial Park 야외극장 옆의 군인 기념 조형물과 단풍나무",
    creator: "Pavan_santhosh.s",
    credit: "Pavan_santhosh.s · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Statue_in_Memorial_park_amphitheatre.jpg",
    commonsPageId: 74687309,
    verifiedAt: "2026-07-28",
    aliases: ["Memorial Park", "Cupertino Memorial Park", "Veterans Memorial Park Cupertino"]
  },
  "redwood-city-downtown-library": {
    src: "assets/places/redwood-city-downtown-library.jpg",
    kind: "actual",
    alt: "광장에서 정면으로 본 Redwood City Main Downtown Library의 아치형 입구",
    creator: "BrokenSphere",
    credit: "BrokenSphere · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Redwood_City_Main_Downtown_Library_front.JPG",
    commonsPageId: 8779298,
    verifiedAt: "2026-07-28",
    aliases: ["Redwood City Downtown Library", "Redwood City Main Downtown Library", "Redwood City Public Library Main"]
  },
  "san-mateo-beresford-park-playground": {
    src: "assets/places/san-mateo-beresford-park-playground.jpg",
    kind: "actual",
    alt: "Beresford Park의 목재 타워와 로프 놀이 구조물을 중심으로 본 놀이터 전경",
    creator: "mliu92",
    credit: "mliu92 · Wikimedia Commons · resized, cropped, and compressed",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Beresford_Park,_San_Mateo._After_the_Cub_Scout_meeting._(40181564422).jpg",
    commonsPageId: 67863631,
    verifiedAt: "2026-07-28",
    aliases: ["Beresford Park Playground", "Beresford Park", "San Mateo Beresford Park"]
  },
  "mountain-view-cuesta-park": {
    src: "assets/places/mountain-view-cuesta-park.jpg",
    kind: "actual",
    alt: "잔디와 큰 나무를 배경으로 보이는 Mountain View Cuesta Park 입구 표지",
    creator: "Jonah Probell",
    credit: "Jonah Probell · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cuesta_Park_entrance_-_panoramio.jpg",
    commonsPageId: 49679122,
    verifiedAt: "2026-07-28",
    aliases: ["Cuesta Park", "Cuesta Park Mountain View", "Mountain View Cuesta Park"]
  },
  "san-jose-almaden-lake-regional-park": {
    src: "assets/places/san-jose-almaden-lake-regional-park.jpg",
    kind: "actual",
    alt: "잔디 언덕에서 산책로와 호수를 함께 내려다본 Almaden Lake Regional Park 전경",
    creator: "Bunty4",
    credit: "Bunty4 · Wikimedia Commons · resized and compressed",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:AlmadenLakePark.jpg",
    commonsPageId: 147098794,
    verifiedAt: "2026-07-28",
    aliases: ["Almaden Lake Regional Park", "Almaden Lake Park", "Almaden Lake Park San Jose"]
  },
  "oakland-zoo": {
    src: "assets/places/oakland-zoo.jpg",
    kind: "actual",
    alt: "동물 조형물과 Oakland Zoo 글자가 보이는 정문 입구",
    creator: "Todd Dailey",
    credit: "Todd Dailey · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Oakland_Zoo_entrance.jpg",
    commonsPageId: 10745944,
    verifiedAt: "2026-07-28",
    aliases: ["Oakland Zoo Children's Zoo", "Wayne and Gladys Valley Children's Zoo", "Oakland Zoo"]
  },
  "berkeley-ohlone-park": {
    src: "assets/places/berkeley-ohlone-park.jpg",
    kind: "actual",
    alt: "산책로에서 운동장 울타리와 잔디 공간을 바라본 Berkeley Ohlone Park",
    creator: "Søren Fuglede Jørgensen, User:Pred",
    credit: "Søren Fuglede Jørgensen (User:Pred) · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ohlone_Park.jpg",
    commonsPageId: 11608452,
    verifiedAt: "2026-07-28",
    aliases: ["Ohlone Park", "Ohlone Park Berkeley", "Berkeley Ohlone Park"]
  },
  "berkeley-codornices-park": {
    src: "assets/places/berkeley-codornices-park.jpg",
    kind: "actual",
    alt: "산책로와 나무 사이로 놀이 구조물과 운동 공간이 보이는 Berkeley Codornices Park 전경",
    creator: "tbo47",
    credit: "tbo47 · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:20220129_Codornices_Park_Berkeley.jpg",
    commonsPageId: 118420514,
    verifiedAt: "2026-07-28",
    aliases: ["Codornices Park", "Codornices Park Berkeley", "Berkeley Codornices Park"]
  },
  "berkeley-live-oak-park": {
    src: "assets/places/berkeley-live-oak-park.jpg",
    kind: "actual",
    alt: "나무 사이에 설치된 Berkeley Live Oak Park 목재 입구 표지",
    creator: "Burkhard Mücke",
    credit: "Burkhard Mücke · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Live_Oak_Park.JPG",
    commonsPageId: 41932746,
    verifiedAt: "2026-07-28",
    aliases: ["Live Oak Park", "Live Oak Park Berkeley", "Berkeley Live Oak Park"]
  },
  "burlingame-main-library-family-place": {
    src: "assets/places/burlingame-main-library-family-place.jpg",
    kind: "actual",
    alt: "정면 출입구와 480 번지 표지가 보이는 Burlingame Public Library Main 외관",
    creator: "Kglavin",
    credit: "Kglavin · Wikimedia Commons · resized and compressed",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Burlingame_Library.JPG",
    commonsPageId: 49914,
    verifiedAt: "2026-07-28",
    aliases: ["Burlingame Public Library, Main", "Burlingame Main Library", "Burlingame Library"]
  }
};

window.LITTLE_WEEKENDS_PLACE_IMAGES = Object.freeze(Object.fromEntries(
  Object.entries(reviewedPlaceImages).map(([id, image]) => [id, {
    ...image,
    reviewFocus: /놀이터|놀이|어린이|도서관|박물관|뮤지엄|동물|입구|정문|건물|전시|공원|산책|호수|광장|농가|해변|기차|회전목마|플라밍고/i.test(image.alt)
      ? "family_decision"
      : "venue_context",
  }]),
));
})();
