window.LITTLE_WEEKENDS_PLACE_IMAGES = Object.freeze({
  "childrens-creativity-museum": {
    src: "assets/places/childrens-creativity-museum.webp",
    kind: "actual",
    alt: "밤에 불이 켜진 Children's Creativity Museum과 회전목마",
    creator: "mliu92",
    credit: "mliu92 · Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Children%27s_Creativity_Museum_(was_%27Zeum%27)_(24969394294).jpg",
    commonsPageId: 47413891,
    verifiedAt: "2026-07-26",
    aliases: ["Children's Creativity Museum"]
  },
  "randall-museum": {
    src: "assets/places/randall-museum.webp",
    kind: "actual",
    alt: "Randall Museum 건물과 입구 표지",
    creator: "Piotrus",
    credit: "Piotrus · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:San_Francisco_-_Randall_Museum_02.JPG",
    commonsPageId: 8825877,
    verifiedAt: "2026-07-26",
    aliases: ["Randall Museum"]
  },
  "san-francisco-zoo": {
    src: "assets/places/san-francisco-zoo.webp",
    kind: "actual",
    alt: "San Francisco Zoo의 플라밍고 전시 공간",
    creator: "Daderot",
    credit: "Daderot · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flamingos_-_San_Francisco_Zoo_-_San_Francisco,_CA_-_DSC03515.jpg",
    commonsPageId: 50254848,
    verifiedAt: "2026-07-26",
    aliases: ["San Francisco Zoo"]
  },
  "childrens-discovery-san-jose": {
    src: "assets/places/childrens-discovery-museum-san-jose.webp",
    kind: "actual",
    alt: "보라색 외관의 Children's Discovery Museum of San Jose",
    creator: "LPS.1",
    credit: "LPS.1 · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Children%27s_Discovery_Museum_of_San_Jose.jpg",
    commonsPageId: 23527205,
    verifiedAt: "2026-07-26",
    aliases: ["Children's Discovery Museum of San Jose"]
  },
  "happy-hollow": {
    src: "assets/places/happy-hollow.webp",
    kind: "actual",
    alt: "Happy Hollow Park & Zoo 입구",
    creator: "Don DeBold",
    credit: "Don DeBold · Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Happy_Hollow_Park_%26_Zoo_-San_Jose,_California,_USA-2Oct2011_(1).jpg",
    commonsPageId: 16856387,
    verifiedAt: "2026-07-26",
    aliases: ["Happy Hollow Park & Zoo"]
  },
  "sfpl-main-library-family-place": {
    src: "assets/places/sfpl-main-library.webp",
    kind: "actual",
    alt: "San Francisco Public Library Main Library 외관",
    creator: "J. Ash Bowie",
    credit: "J. Ash Bowie · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:SFPL_Main_Library_Full_Exterior.jpg",
    commonsPageId: 4567449,
    verifiedAt: "2026-07-26",
    aliases: ["SFPL Main Library", "San Francisco Public Library Main Library"]
  },
  "hiller-aviation": {
    src: "assets/places/hiller-aviation-museum.webp",
    kind: "actual",
    alt: "Hiller Aviation Museum의 초기 항공기 전시",
    creator: "Ed Bierman",
    credit: "Ed Bierman · Wikimedia Commons",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Early_Flight_(3029749435).jpg",
    commonsPageId: 26445992,
    verifiedAt: "2026-07-26",
    aliases: ["Hiller Aviation Museum"]
  },
  "emma-prusch-farm": {
    src: "assets/places/emma-prusch-farm.webp",
    kind: "actual",
    alt: "Emma Prusch Farm Regional Park의 역사적인 농가",
    creator: "Grey3k",
    credit: "Grey3k · Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:EmmaPruschFarmhouse.jpg",
    commonsPageId: 4732779,
    verifiedAt: "2026-07-26",
    aliases: ["Emma Prusch Farm Regional Park"]
  },
  "lawrence-hall-science": {
    src: "assets/places/lawrence-hall-of-science.webp",
    kind: "actual",
    alt: "언덕 위 The Lawrence Hall of Science 건물",
    creator: "Lasthib",
    credit: "Lasthib · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2018_Lawrence_hall_of_science_Berkeley.jpg",
    commonsPageId: 71696449,
    verifiedAt: "2026-07-26",
    aliases: ["The Lawrence Hall of Science", "Lawrence Hall of Science"]
  },
  "tilden-little-farm": {
    src: "assets/places/tilden-little-farm.webp",
    kind: "actual",
    alt: "Tilden Little Farm의 헛간과 농장 동물",
    creator: "Harmonywriter",
    credit: "Harmonywriter · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tilden_Regional_Park_little_farm.jpg",
    commonsPageId: 29716241,
    verifiedAt: "2026-07-26",
    aliases: ["Tilden Little Farm"]
  },
  "lindsay-wildlife": {
    src: "assets/places/lindsay-wildlife.webp",
    kind: "actual",
    alt: "Lindsay Wildlife Experience에서 보호 중인 회색여우",
    creator: "Milonica",
    credit: "Milonica · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gray_Fox_in_captivity.JPG",
    commonsPageId: 23415312,
    verifiedAt: "2026-07-26",
    aliases: ["Lindsay Wildlife Experience"]
  },
  "redwood-shores-library": {
    src: "assets/places/redwood-shores-library.webp",
    kind: "actual",
    alt: "Redwood Shores Branch Library 내부 열람 공간",
    creator: "Suiren2022",
    credit: "Suiren2022 · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Redwood_Shores_Branch_Library_-_2.jpg",
    commonsPageId: 136189785,
    verifiedAt: "2026-07-26",
    aliases: ["Redwood Shores Branch Library"]
  },
  "foster-city-library-family-place": {
    src: "assets/places/foster-city-library.webp",
    kind: "actual",
    alt: "Foster City Library 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Foster_City_Library,_exterior_(November_2024)_02.jpg",
    commonsPageId: 155533973,
    verifiedAt: "2026-07-26",
    aliases: ["Foster City Library"]
  },
  "belmont-library-family-place": {
    src: "assets/places/belmont-library.webp",
    kind: "actual",
    alt: "Belmont Library 건물과 표지",
    creator: "Mike Linksvayer",
    credit: "Mike Linksvayer · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Belmont_Library_(8017936131).jpg",
    commonsPageId: 50288500,
    verifiedAt: "2026-07-26",
    aliases: ["Belmont Library"]
  },
  "sonoma-traintown": {
    src: "assets/places/sonoma-traintown.jpg",
    kind: "actual",
    alt: "Sonoma TrainTown Railroad의 증기 기관차와 회전 관람차",
    creator: "Jeff Soares",
    credit: "Jeff Soares · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:TrainTowntrain.JPG",
    commonsPageId: 7758639,
    verifiedAt: "2026-07-27",
    aliases: ["Sonoma TrainTown Railroad", "TrainTown"]
  },
  "childrens-fairyland": {
    src: "assets/places/childrens-fairyland.jpg",
    kind: "actual",
    alt: "오클랜드 Children's Fairyland 입구 안내 표지",
    creator: "Ted Eytan",
    credit: "Ted Eytan · Wikimedia Commons",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Childrens_Fairyland_Oakland_7315_(6525735831).jpg",
    commonsPageId: 23144222,
    verifiedAt: "2026-07-27",
    aliases: ["Children's Fairyland"]
  },
  "san-carlos-library-family-place": {
    src: "assets/places/san-carlos-library.jpg",
    kind: "actual",
    alt: "San Carlos Library 정면 입구와 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:San_Carlos_Library,_exterior_(November_2024).jpg",
    commonsPageId: 154924155,
    verifiedAt: "2026-07-27",
    aliases: ["San Carlos Library"]
  },
  "millbrae-library-family-place": {
    src: "assets/places/millbrae-library.jpg",
    kind: "actual",
    alt: "Millbrae Library 정면 입구와 벽면 표지",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Millbrae_Library,_exterior_(October_2024)_01.jpg",
    commonsPageId: 154673287,
    verifiedAt: "2026-07-27",
    aliases: ["Millbrae Library"]
  },
  "mountain-view-public-library-family-place": {
    src: "assets/places/mountain-view-public-library.jpg",
    kind: "actual",
    alt: "Pioneer Memorial Park에서 바라본 Mountain View Public Library 외관",
    creator: "BriefEdits",
    credit: "BriefEdits · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mountain_View_Public_Library,_exterior_(April_2024)_01.jpg",
    commonsPageId: 166522867,
    verifiedAt: "2026-07-27",
    aliases: ["Mountain View Public Library"]
  },
  "los-gatos-library-family-place": {
    src: "assets/places/los-gatos-library.jpg",
    kind: "actual",
    alt: "나무 뒤로 보이는 Los Gatos Library 정면 외관",
    creator: "Ramkmeno",
    credit: "Ramkmeno · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Los_Gatos_Library.jpg",
    commonsPageId: 72980471,
    verifiedAt: "2026-07-27",
    aliases: ["Los Gatos Library"]
  },
  "sunnyvale-public-library-family-place": {
    src: "assets/places/sunnyvale-public-library.jpg",
    kind: "actual",
    alt: "Sunnyvale Public Library 정면 출입구",
    creator: "The Sands of Time 0",
    credit: "The Sands of Time 0 · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunnyvale_Public_Library_(January_2025).jpg",
    commonsPageId: 167167207,
    verifiedAt: "2026-07-27",
    aliases: ["Sunnyvale Public Library"]
  },
  "campbell-campbell-park": {
    src: "assets/places/campbell-park.jpg",
    kind: "actual",
    alt: "Campbell Park 입구 표지와 공원 산책로",
    creator: "Grendelkhan",
    credit: "Grendelkhan · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Entrance_to_Campbell_Park.jpg",
    commonsPageId: 146402042,
    verifiedAt: "2026-07-27",
    aliases: ["Campbell Park"]
  },
  "oakland-lincoln-square-park": {
    src: "assets/places/lincoln-square-park-oakland.jpg",
    kind: "actual",
    alt: "오클랜드 Lincoln Square Park의 벽화와 놀이터",
    creator: "Mliu92",
    credit: "Mliu92 · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lincoln_Square_Park,_Oakland.jpg",
    commonsPageId: 132448895,
    verifiedAt: "2026-07-27",
    aliases: ["Lincoln Square Park"]
  },
  "daly-city-gellert-park": {
    src: "assets/places/gellert-park.jpg",
    kind: "actual",
    alt: "나무 사이로 보이는 Gellert Park 운동장과 놀이 공간",
    creator: "Clyde Charles Brown",
    credit: "Clyde Charles Brown · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gellert_Park,_Daly_City,_California,_US.jpg",
    commonsPageId: 164230126,
    verifiedAt: "2026-07-27",
    aliases: ["Gellert Park"]
  },
  "south-san-francisco-orange-memorial-park": {
    src: "assets/places/orange-memorial-park.jpg",
    kind: "actual",
    alt: "Orange Memorial Park 잔디밭과 어린이 놀이터",
    creator: "BrokenSphere",
    credit: "BrokenSphere · Wikimedia Commons",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Orange_Memorial_Park_1.JPG",
    commonsPageId: 11430891,
    verifiedAt: "2026-07-27",
    aliases: ["Orange Memorial Park"]
  },
  "los-gatos-oak-meadow-park-playground": {
    src: "assets/places/oak-meadow-park.jpg",
    kind: "actual",
    alt: "Oak Meadow Park의 Billy Jones Wildcat Railroad 역",
    creator: "Gregory Ford Henderson",
    credit: "Gregory Ford Henderson · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Billy_Jones_Railroad_station_in_Oak_Meadow_Park_Adjacent_to_Vasona_Lake_County_Park.jpg",
    commonsPageId: 120228146,
    verifiedAt: "2026-07-27",
    aliases: ["Oak Meadow Park Playground", "Oak Meadow Park"]
  },
  "alameda-lincoln-park": {
    src: "assets/places/lincoln-park-alameda.jpg",
    kind: "actual",
    alt: "알라메다 Lincoln Park의 배 모양 어린이 놀이터",
    creator: "Mliu92",
    credit: "Mliu92 · Wikimedia Commons",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lincoln_Park_7.jpg",
    commonsPageId: 132448886,
    verifiedAt: "2026-07-27",
    aliases: ["Lincoln Park"]
  },
  "mountain-view-mariposa-park": {
    src: "assets/places/mariposa-park.jpg",
    kind: "actual",
    alt: "Mariposa Park의 어린이 놀이터와 잔디 산책로",
    creator: "Steven Baltakatei Sandoval",
    credit: "Steven Baltakatei Sandoval · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mariposa_Park,_Mountain_View,_California,_March_2019.jpg",
    commonsPageId: 77387532,
    verifiedAt: "2026-07-27",
    aliases: ["Mariposa Park"]
  },
  "los-gatos-vasona-lake-county-park": {
    src: "assets/places/vasona-lake-county-park.jpg",
    kind: "actual",
    alt: "Vasona Lake County Park의 넓은 잔디밭과 나무",
    creator: "Gregory Ford Henderson",
    credit: "Gregory Ford Henderson · Wikimedia Commons",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vasona_Lake_County_Park_meadow_with_geese.jpg",
    commonsPageId: 120228151,
    verifiedAt: "2026-07-27",
    aliases: ["Vasona Lake County Park"]
  },
  "oakland-mosswood-park": {
    src: "assets/places/mosswood-park.jpg",
    kind: "actual",
    alt: "오클랜드 Mosswood Park의 잔디밭과 큰 나무",
    creator: "Mx. Granger",
    credit: "Mx. Granger · Wikimedia Commons",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mosswood_Park_1.jpg",
    commonsPageId: 134783526,
    verifiedAt: "2026-07-27",
    aliases: ["Mosswood Park"]
  }
});
